# Generated by Django 4.2 on 2024-07-20 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0002_historial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productos',
            old_name='Descripcion',
            new_name='descripcion',
        ),
    ]
