# Generated by Django 4.2 on 2024-08-15 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0004_remove_productos_valoracion_productos_search_vector_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='imagen',
            field=models.URLField(blank=True, null=True),
        ),
    ]
