# Generated by Django 4.2 on 2024-08-15 21:15

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0005_productos_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('name_producto', models.CharField(max_length=30)),
                ('descripcion', models.TextField(default='Lorem ipsum dolor sit, amet consectetur adipisicing elit. Sequi, beatae. Nobis adipisci sint assumenda? Culpa beatae, fugiat et, eos, blanditiis eligendi sint odit pariatur soluta dolor delectus nam iure iusto.', max_length=255)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad_disponible', models.IntegerField()),
                ('imagen', models.URLField(blank=True, null=True)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='historial',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='historial',
            name='usuario',
        ),
        migrations.RemoveIndex(
            model_name='productos',
            name='Tienda_prod_search__d80043_gin',
        ),
        migrations.RemoveIndex(
            model_name='productos',
            name='idx_products_trigram',
        ),
        migrations.DeleteModel(
            name='Historial',
        ),
        migrations.AddField(
            model_name='products',
            name='categoria_producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tienda.categoria_producto'),
        ),
        migrations.AddField(
            model_name='products',
            name='proovedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tienda.proovedores'),
        ),
        migrations.AddIndex(
            model_name='products',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='Tienda_prod_search__61cd53_gin'),
        ),
        migrations.AddIndex(
            model_name='products',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name_producto'], name='idx_products_trigram', opclasses=['gin_trgm_ops']),
        ),
    ]
