# Generated by Django 4.2 on 2024-08-15 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SistemaComentarios', '0005_alter_comentarios_producto'),
        ('Carro_de_compras', '0009_alter_carro_compra_producto_alter_whishlist_producto'),
        ('Tienda', '0006_products_remove_historial_producto_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Productos',
        ),
    ]
