# Generated by Django 4.2 on 2024-08-23 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0007_delete_productos'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='valoracion',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
        ),
    ]
