# Generated by Django 4.2 on 2024-08-24 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0008_products_valoracion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='valoracion',
            new_name='rating',
        ),
    ]
