# Generated by Django 4.2 on 2024-07-21 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Autenticacion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuarios',
            old_name='id_usuario',
            new_name='id',
        ),
    ]
