# Generated by Django 4.2 on 2024-08-09 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Autenticacion', '0003_remove_usuarios_targeta_alter_usuarios_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='verify_email',
            field=models.BooleanField(default=False),
        ),
    ]
