# Generated by Django 4.2 on 2024-08-09 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Autenticacion', '0005_alter_usuarios_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuarios',
            old_name='verify_email',
            new_name='email_verified',
        ),
    ]
