# Generated by Django 4.2 on 2023-09-01 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Carro_de_compras', '0002_carro_compra_cantidad_del_producto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carro_compra',
            name='cantidad_del_producto',
            field=models.IntegerField(default=1),
        ),
    ]
