# Generated by Django 4.2 on 2024-07-20 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Carro_de_compras', '0005_rename_wishlist_whishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carro_compra',
            name='precio_total',
        ),
        migrations.AlterField(
            model_name='carro_compra',
            name='cantidad_del_producto',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
