# Generated by Django 4.2 on 2024-07-23 20:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Carro_de_compras', '0006_remove_carro_compra_precio_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carro_compra',
            name='cantidad_del_producto',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
    ]
