# Generated by Django 4.2 on 2024-07-23 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Carro_de_compras', '0007_alter_carro_compra_cantidad_del_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carro_compra',
            name='cantidad_del_producto',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
