# Generated by Django 4.2 on 2024-08-25 22:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Tienda', '0009_rename_valoracion_products_rating'),
        ('Carro_de_compras', '0009_alter_carro_compra_producto_alter_whishlist_producto'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='carro_compra',
            unique_together={('usuario', 'producto')},
        ),
        migrations.AlterUniqueTogether(
            name='whishlist',
            unique_together={('usuario', 'producto')},
        ),
    ]
