# Generated by Django 4.2 on 2024-08-25 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Carro_de_compras', '0010_alter_carro_compra_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='carro_compra',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='whishlist',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='carro_compra',
            constraint=models.UniqueConstraint(fields=('usuario', 'producto'), name='unique_usuario_producto_carro_compra'),
        ),
        migrations.AddConstraint(
            model_name='whishlist',
            constraint=models.UniqueConstraint(fields=('usuario', 'producto'), name='unique_usuario_producto_whishlist'),
        ),
    ]
