# Generated by Django 4.2 on 2024-07-26 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SistemaComentarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentarios',
            name='comentario',
        ),
        migrations.RemoveField(
            model_name='comentarios',
            name='comentario_contenido',
        ),
        migrations.AddField(
            model_name='comentarios',
            name='post',
            field=models.TextField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='comentarios',
            name='dislikes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='comentarios',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
