# Generated by Django 4.2 on 2024-07-29 16:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SistemaComentarios', '0002_remove_comentarios_comentario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentarios',
            name='hora_publicacion',
            field=models.TimeField(auto_now_add=True, default=datetime.datetime(2024, 7, 29, 16, 55, 20, 760934, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
