# Generated by Django 4.2 on 2024-07-29 19:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SistemaComentarios', '0003_comentarios_hora_publicacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentarios',
            name='fecha_publicacion',
        ),
        migrations.RemoveField(
            model_name='comentarios',
            name='hora_publicacion',
        ),
        migrations.AddField(
            model_name='comentarios',
            name='publicacion',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 7, 29, 19, 59, 42, 539228, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
