# Generated by Django 4.2 on 2024-08-15 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0006_products_remove_historial_producto_and_more'),
        ('SistemaComentarios', '0004_remove_comentarios_fecha_publicacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentarios',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tienda.products'),
        ),
    ]
