# Generated by Django 4.2 on 2024-08-23 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SistemaComentarios', '0005_alter_comentarios_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentarios',
            name='valorarion',
            field=models.DecimalField(decimal_places=1, default=5, max_digits=2),
        ),
    ]
