# Generated by Django 4.2 on 2024-08-24 08:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SistemaComentarios', '0006_comentarios_valorarion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentarios',
            old_name='valorarion',
            new_name='rating',
        ),
        migrations.RemoveField(
            model_name='comentarios',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='comentarios',
            name='likes',
        ),
        migrations.AddField(
            model_name='comentarios',
            name='title',
            field=models.CharField(default='Un producto muy interesante', max_length=50),
        ),
        migrations.AlterField(
            model_name='comentarios',
            name='post',
            field=models.TextField(default='', max_length=360),
        ),
        migrations.CreateModel(
            name='Helpful',
            fields=[
                ('id_helpful', models.AutoField(primary_key=True, serialize=False)),
                ('comentario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SistemaComentarios.comentarios')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
