# Generated by Django 4.2 on 2024-08-25 22:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SistemaComentarios', '0007_rename_valorarion_comentarios_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentarios',
            name='post',
            field=models.TextField(default='Hello I love this product', max_length=360),
        ),
        migrations.AlterUniqueTogether(
            name='helpful',
            unique_together={('usuario', 'comentario')},
        ),
    ]
