# Generated by Django 4.2 on 2024-08-25 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SistemaComentarios', '0009_alter_helpful_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='helpful',
            name='unique_usuario_comentario',
        ),
        migrations.AddConstraint(
            model_name='helpful',
            constraint=models.UniqueConstraint(fields=('usuario', 'comentario'), name='unique_usuario_comentario_helpful'),
        ),
    ]
